# Generated by Django 3.2 on 2022-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=125, verbose_name='店铺的名称')),
                ('score', models.IntegerField(default=100, verbose_name='商品得分')),
                ('title', models.CharField(max_length=225)),
                ('goods_image', models.TextField(verbose_name='展示图片')),
                ('shop', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
